### ISSUE TITLE
Snort error 

### ISSUE THREAD

**Issue by mimimns666** [Cisco-Talos/snort-faq#21]
im installing Snort for a demonstration of ids and while trying to run i get this error:

ERROR: /etc/snort/rules/alerts.rules(3) rule threshold has incorrect argument count; should be 4 pairs.
Fatal Error, Quitting..

and this is the rules file :

alert icmp any any -> $HOME_NET any (msg:"Someone is pinging"; itype:8; sid:1000000;)

alert tcp any any -> $HOME_NET 80 (flags: S; msg:"Possible TCP Dos !! BE CAREFULL !!"; flow: stateless; threshold: type both, track by_dst, count 10, seconds 10, sid:1000001; rev:1;)

alert tcp any any -> 10.0.2.15 22 (msg:"SSH Connection is detected"; sid:1000002;)

i dont understand what is wrong with it and what they mean with 4 pairs i've looked up this everywhere but i cant find anything how can i solve this ??

**Comment by vrtadmin** [comment]
Thank you for your interest in Snort.  This isn't the appropriate place to ask questions, this is for edits to the FAQ. We have thousands of people subscribed to our mailing lists, and it's better if you submit your questions to the appropriate mailing list at:

https://www.snort.org/community

Please check out our Snort-Users mailing list there!  Thanks!

**Comment by vrtadmin** [comment]
>  threshold: type both, track by_dst, count 10, seconds 10, 

However, I just noticed you don't have a semi colon at the end of your threshold statement (seconds 10).  You have a comma.
